# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

# controllers:
#     resource: routing.controllers

controllers:
    resource: ../src/Controller/
    type: attribute
    # prefix: /{_locale}
    requirements:
        _locale: en|fr
    defaults:
        _locale: fr


# Cette route doit être la dernière (capture tout)
error_redirect:
    path: /{any}
    controller: App\Controller\ErrorController::redirectToHome
    requirements:
        any: '.*'

# error_redirect:
#     path: /{any}
#     controller: App\Controller\ErrorController::redirectToHome
#     requirements:
#         any: '.*'
    # priority: -10

# Route par défaut pour les pages non trouvées (optionnel)
# fallback:
#     path: /{any}
#     controller: App\Controller\ErrorController::fallback
#     requirements:
#         any: '.*'



# admin:
#     resource: '@EasyAdminBundle/Controller/EasyAdminController.php'
#     prefix: /admin
#     type: annotation

# controllers:
#     resource: ../src/Controller/
#     type: attribute
