# config/services.yaml
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Déclaration explicite du contrôleur d'erreur
    App\Controller\ErrorController:
        public: true
        tags: ['controller.service_arguments']